name: Sync to Hugging Face Hub
on:
  push:
    branches: ["**"] # Sync all branches
    tags: ["**"]     # Sync all tags

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configure dummy user for push if needed
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Add Hugging Face as a remote
          git remote add hf https://Bishal26:$HF_TOKEN@huggingface.co/spaces/Bishal26/chess_game_bishal
          
          # Mirror all branches and tags
          git push hf --all --force
          git push hf --tags --force
